### PR TITLE
add 7th combo point

### PR DESCRIPTION
**Pull request by jdaytona**
mot much of a lua programmer but added a 7th combo point

### CODE REVIEW

**Comment by Backupiseasy** [comment]
Seems fine like my own version :)

**Comment by Backupiseasy** [comment]
Do you get Lua errors also with 6 combo points? It does not seem so as this pull request would not fix this.

**Comment by jdaytona** [comment]
Hi Backupiseasy!
No, I was only getting errors when hitting 7 combo points and these changes seemed to make everything alright. I can test again here after work in around 2 hours or so if you'd like confirmation. Thanks for looking  =)

**Comment by Backupiseasy** [comment]
You‘re welcome. Thanks for your pull request as well. I just had already made the same changes, so I didn‘t merge it.

**Pull request closed without merging**
