### PR TITLE
Update ThreatClassic-1.0 to LibThreatClassic2

### PR DESCRIPTION
**Pull request by dfherr**
Hi,

ThreatClassic-1.0 has a ton of bugs and the author seems to have abandoned the project (unreachable and no update for 3 months). This PR updates the lib to a newer version from my development.

I created https://github.com/dfherr/LibThreatClassic2 which fixes various bugs. Most notably Warrior tanks correctly get 15% increased threat from Defiance instead of 25% and a message bug in alterac valley was fixed that spams the chat with "You are not in a raid group".

The newest details also updated to LibThreatClassic2 https://www.curseforge.com/wow/addons/details-damage-meter-classic-wow/

Some notes on the diffs:

* I moved the Ace3 dependencies inside of the lib as they are needed by the lib and addons not running ace complained. So you will see new Ace3 files making this diff huge.
* The diff includes all updates from ThreatClassic-1.0 to LibThreatClassic2, which sums up to about 20 individual fixes and a rewrite of the NPC module logic
* I only updated the lib files and name and didn't touch your version number or changelog.

### CODE REVIEW

**Comment by dfherr** [comment]
@Backupiseasy Thanks for updating. So i guess this can be closed :)?

**Comment by Backupiseasy** [comment]
Yes, it can be closed.

Am Sa., 28. Dez. 2019 um 19:00 Uhr schrieb Dennis-Florian Herr <
notifications@github.com>:

**Comment by Backupiseasy** [comment]
Ah, I did not get a notification of your pull request yesterday. I already
got an issue report regarding this (from you?), that's why I fixed it
already yesterday without looking at your pull request.

Am Sa., 28. Dez. 2019 um 20:22 Uhr schrieb Threat Plates <
threatplates@gmail.com>:

**Comment by dfherr** [comment]
Nope, wasn't me on curse. The guy on curse also linked to the addon, not the library project. Just for reference this is the library https://github.com/dfherr/LibThreatClassic2 (revision 5, the addon is version 2.07).

 The PR was actually one day earlier. But it doesn't surprise me. There are quite a lot of people annoyed by the buggy library and asking across multiple channels ;)

**Comment by dfherr** [comment]
@Backupiseasy Nope, wasn't me on curse. The guy on curse also linked to the addon, not the library project. Just for reference this is the library https://github.com/dfherr/LibThreatClassic2 (revision 5, the addon is version 2.07).

The PR was actually one day earlier. But it doesn't surprise me. There are quite a lot of people annoyed by the buggy library and asking across multiple channels ;)

**Pull request closed without merging**
