### PR TITLE
Add enemy name abbreviation option

### PR DESCRIPTION
**Pull request by jsocol**
I took a crack at #270. Not sure if this is the direction you'd want to go in general, or if there are specific tweaks you'd like to see. Happy to try to follow whatever you had in mind, either way!

I only applied this to enemy units and healthbar view because that seemed like the most pressing place to save space and abbreviating seemed kind of antithetical to "headline" view. But it should be easy to extend to friendly units, headline view, etc, if you'd like.

### CODE REVIEW

**Comment by Backupiseasy** [comment]
Sorry for not anwering sooner. This looks promising and I should have time to look into it in the upcoming days.

**Comment by jsocol** [comment]
No worries at all, as a fellow open source maintainer 🙂 Appreciate your time whenever!

**Comment by Backupiseasy** [comment]
So, finally, I'll add that to 10.3. I changed some stuff, see commit messages.

What do you think about the following: Should abbreviation be disabled for players?

**Comment by Backupiseasy** [comment]
An additional improvement would be to use abbreviation only when the text is longer than the text box.

**Pull request merged**
