### PR TITLE
Hiding Guardian "pets" and Overriding of General "Hide Nameplate" Settings with Custom Nameplates

### PR DESCRIPTION
**Pull request by ManneN1**
Hello,

This PR accomplishes two things:
- Adds the option to hide "Guardian" units (more on why this is "needed" below)
- Enables the user to override the general "Hide Nameplates" options with custom nameplates, if wanted (with a toggle).

There are many situations in which a player may want to see a few guardian units, but not the vast majority. E.g. in PvP a user may want to hide Mirror Image or Earth, Storm, and Fire clones (which do not have distinct names, they have the same name as their caster) and most other guardians, whereas Abomination and a few others are very important to see.

In such situations a whitelist approach is wanted. 

The CVar for "Show Enemy Guardian Units" can in this scenario not be turned off (as some guardians must be shown), but a generic "Hide Guardian Units" can be used to enable a whitelist/blacklist-like behaviour when used in combination with custom plates. Lastly, an option for "Allow overriding of general hidden nameplate options" was added for more customization (disabling any residual/long forgotten custom plates from showing if the general option of hiding has been chosen).

### CODE REVIEW

**Comment by Backupiseasy** [comment]
I like this change. The basic idea, to only show selected Guardian units, does make a lot of sense. There are two things I am still thinking about:
* I don't think that the override is necessary. I think it should be the default behaviour actually. Why would you disable it? Disabling means that all units would be hidden that are enabled under Hidden Units. But then you would not need any custom nameplates anyway, right? Unless you only want to do this temporarily. You could just disable all custom nameplates relating to the hidden units. Bit more work, but with the same result.
* Having an enable button under Visiblity  and a Hide button under Hidden Units for Guardians does not feel right. If you don't want to see Guardian units why not just disable them under Visibility. Obviously, if the CVar would be disabled, nameplates for Guardian units will be disabled and custom nameplates would not work any longer. That's why you made this PR. Still, having an enable and hide button, does not seem right. I have no better solution right now as the one you implemented, but that's what I am thinking about. A solution would be not to disable the CVar nameplateShowFriendlyGuardians when Guardian units are disabled, but to just hide the nameplates (something that could be done for all unit types as custom nameplates would work then), but it does not seem efficient to do so.

Looking forward to hear your opinion on this.

**Comment by ManneN1** [comment]
Hello,

- I agree with your first bullet. I just wanted to add the "option" as to make my PR as non-intrusive to people's current UI's as possible. But yes, in my opinion all custom nameplates should override the other settings, so to speak. If you don't want a custom nameplate - remove it. Do you want me to update the PR with this (I.e. revert the... last (?) commit).

- As to your second bullet I had three thoughts on how to do this: 
1. Have two different toggles, one for the cvar and one for showing/hiding them when the cvar is enabled.
2. You could possibly add a toggle in each custom nameplate "is this a guardian unit?" and then you'd toggle the cvar in the code based on if there are any enabled custom nameplates with the "is this a guardian unit" set to true.
3. You could have the cvar enabled at all times and just have the "Hide Guardian Units" toggle option. As you said, this could even be extended to all unit type cvars.

I thought 1. was the least intrusive in terms of "awkwardness" and/or performance.

Again, I tried to make the PR very non-intrusive with no / few "big" decisions. Deciding to go with option 3 would be a bigger thing which I don't think I could code (I'm not that familiar with the code base) and it would have performance implications that I think you should take the decision on.

**Comment by Backupiseasy** [comment]
I made some changes to your code and created a pull request to your rep. Not sure if that's the best way, but I cannot change this PR directly I think. Comments are in the PR https://github.com/ManneN1/ThreatPlates/pull/1

**Comment by ManneN1** [comment]
I think you should be able to make changes to this PR directly (at least I chose that option). Regardless, I have accepted your PR. :)

Thanks, this is much appreciated by many PvPers!

**Pull request merged**
