### PR TITLE
Quest Widget changes

### PR DESCRIPTION
**Pull request by Kungfumoo**
questdetails

Implements the above where applicable.
This can be toggled off and on via the 'Quest details' option.

This is done by using an internal table called 'Quests' which is built when the player enables the widget or logs in with it enabled.

Quests contains the objective information, including it's type.

Player picking up quests and removing them(by handing in, abandon etc) will just alter this internal table.

As discussed in discord, I changed the way the quest widget updates now. Instead of updating on QUEST_WATCH_UPDATE, it updates on QUEST_LOG_UPDATE now.

QUEST_WATCH_UPDATE adds 'dirty' quests to a list QuestsToUpdate which QUEST_LOG_UPDATE will parse and update the Quests table. As pointed out in discord QUEST_LOG_UPDATE fires a lot, it will only do work on the plates if there is quests to update.

Improvements we could do is update only the affected plates, instead of mass updating all of them whenever a quest objective needs updating.

### CODE REVIEW

**Comment by Kungfumoo** [comment]
If you want to fix the delay issue in now in devel/90. Something like:
```lua
local toUpdate = false

function Widget:QUEST_WATCH_UPDATE()
  toUpdate = true
end

function Widget:QUEST_LOG_UPDATE()
  if toUpdate then
    self:UpdateAllFramesAndNameplateColor()
    toUpdate = false
  end
end
```

should do the trick

**Comment by Backupiseasy** [comment]
Hm, in world quests today, no quest progress/details were shown for me. Created a new profile and reloaded UI. Still to details ...

It seems to be related to the following line: 
`local current, goal, objectiveName = string.match(progress, "^(%d+)/(%d+) (.+)$")`
The variables current and goal are nil, even on a kill quest mob for a worldquest. The tooltip text is " - Kopfjägerin Lee'za getötet: 0/1"
Maybe the format is different in English, not sure. But at least in German, current/goal are at the end, not the object. 

Some things I saw while looking into the code:
* Options:
  * I recommend to move "Show Quest Details" to Visibility, maybe with a shorter name like just "(Quest) Progress".
  * I also would rename the settings variable to ShowProgess.
* Please use object-orientied syntax for functions as much as possible.
  * Like: `function Widget:<name>(arg1, arg2, ...)`
  * It's better for performance wise, as far as I know. Also, because you now can define variables like Quests, QuestToUpdate as class variables of Widget, e.g., Widget.Quests = {}. That way you can access them within functions with self.Quests. That avoida accessing file-global variables.
* Move number-conversion out of UpdateFrame. Doing that when creating the current array avoids multiple conversions in UpdateFrame.
* Why do you check for widget_frame.Text? It's created in Create() and should never be nil.
* You could avoid the if-then-else structure for the type-icon by renmaing the icons to monster/item and using a hash table for getting the icon. All other types will return nil which will remove the texture I think.  
* Now to an update problem I can imagine although not sure if it really will ever happen:
  * If  a unit is the target for several quest (at the same time or one after the other), what happens? Assume now that one quest (type monster) is completed, but the other one (no type) remains or is added newly? Would that not lead to wrong positioning as OnUnitAdded is not called in this scenario?
  * If type is neither monster nor item you should hide the texture anyway or set it to nil, as otherwise it might be still be set to an icon, if the frame is re-used, right?
  * You should move the positioning code for Text/TypeTexture to UpdateFrame. 
* You should not set alpha/scale for Text/TypeTexture unless you want it to be different from widget_frame. They are updated with widget_frame.
* Declare all API functions that are called often as local file variables like "local GetQuestLogTitle = GetQuestLogTitle"

Ah, that's a lot. I am sorry :}

**Comment by Kungfumoo** [comment]
No need to apologise, this is great, thanks :)

Ill take a look and answer any queries later on. And do any work required

**Comment by Kungfumoo** [comment]
I didn't implement percentages. Can add that too

**Comment by Kungfumoo** [comment]
> The variables current and goal are nil, even on a kill quest mob for a worldquest. The tooltip text is " - Kopfjägerin Lee'za getötet: 0/1" Maybe the format is different in English, not sure. But at least in German, current/goal are at the end, not the object.

Woops didn't consider formats in other languages. Yeah it works fine in English.
GetQuestObjectiveInfo() I believe returns numFulfilled and numRequired so ill use them instead.
Ill work out something else for the key.

> Why do you check for widget_frame.Text? It's created in Create() and should never be nil.

There used to be a case where it would be null but I changed that and forgot to take these out. Will fix

> You could avoid the if-then-else structure for the type-icon by renaming the icons to monster/item and using a hash table for getting the icon. All other types will return nil which will remove the texture I think.

I think I did try this and I got green squares showing ingame on quests that don't need an icon. But will have a play.

> if a unit is the target for several quest (at the same time or one after the other), what happens? Assume now that one quest (type monster) is completed, but the other one (no type) remains or is added newly? Would that not lead to wrong positioning as OnUnitAdded is not called in this scenario?

So the tooltip logic in IsQuestUnit still dictates which objective information is loaded onto the plate, and will only pick the first of many objectives, until that objective completes. On the next plate refresh it should in theory just load the next objective. I've not actually tested this scenario yet though ill see if I can replicate this on a low level character. You're right about OnUnitAdded.

> You should not set alpha/scale for Text/TypeTexture unless you want it to be different from widget_frame. They are updated with widget_frame.

Yep my bad, they are inherited. The scale settings need to stay but Ill remove the alpha sets.

Everything else I agree. You happy with me to do this work then?

**Comment by Backupiseasy** [comment]
Absolutely!

**Comment by Kungfumoo** [comment]
Just giving an update: Hoping to finish this week. I've been away on holiday so have not done any work on it for a while.

**Comment by Kungfumoo** [comment]
Ok this is done.

Area Progress (%) has been implemented, however it still uses the tooltip as it's primary source of information.

I've not found a way via the API to get this information. GetQuestObjectiveInfo() numFulfilled and numRequired does not seem to return the correct information for area progress

**Pull request merged**
