### PR TITLE
Import/Export threatplate settings

### PR DESCRIPTION
**Pull request by Kungfumoo**
Adds the ability to Import/Export a threatplates 'profile' as a string (much like weakauras).

**This adds two libraries to threatplates:**

- AceSerializer3.0 (https://www.wowace.com/projects/ace3/pages/api/ace-serializer-3-0)
   - Used to serialize tables into strings
- LibDeflate(https://github.com/SafeteeWoW/LibDeflate)
   - Used to take the large serialized strings and compress them

Both of these libraries are also used in weakauras.

**How it works**
tpix1

This work adds two buttons to the 'profile' window of threatplates options.

"Export Current Profile" simply takes the currently loaded profile and serializes it as a string that can be copied:
tpix2

"Import Current Profile" just opens an empty copy frame. User will paste the serialized string in it.
tpix3

When the user hits 'close' it will create a new profile using the new settings called 'imported profile'
**The user's old profile is unaffected**

**Future Work:**

- As discussed on discord, making it more granular so you can export specific settings is definitely possible.
- A nice way to display errors. I took a look at weakauras and pasting invalid strings yields nothing spectacular. Atm it is just printing text in the chat window when an import has failed.

A test string which loads horrible nameplates with massive quest icons that are red:
https://gist.githubusercontent.com/Kungfumoo/0b1a8f4bbdb39d844a82262096d4eb93/raw/95c85f08a2dc91e1e0484a4fb56fc8657da84eee/gistfile1.txt

### CODE REVIEW

**Comment by Backupiseasy** [comment]
Hm, did not want to close this. Any ideas how to re-open it?

**Comment by gall-levi-code** [comment]
Only the owner can click on the 're-open and comment' button at the bottom.

**Comment by Kungfumoo** [comment]
Hmm trying to find that!

**Comment by Kungfumoo** [comment]
Can you try now? I've enabled edits from maintainers.

I can't see this 're-open and comment' button

**Comment by Backupiseasy** [comment]
Still not able to re-open it. The button is grey-out out. I guess I'll use my local copy of this pull request and merge it locally. That should work as well.

**Comment by Backupiseasy** [comment]
Hah, I pushed a new 9.2 branch and now the pull request can be re-opend.

**Comment by Backupiseasy** [comment]
Ok, I merged this pull request now into the current 9.2 branch - not in the correct way, I think, but it's in there at least :)

**Comment by Backupiseasy** [comment]
Two things we should add until releasing this, I think, are:
- Add an import/export function for (all) custom nameplates - that's often requested.
- Add versioning so that you don't import a deprecated export string. idea for that: Wrap the profile table into a table with a version number (current TP version, e.g.,)

**Comment by Backupiseasy** [comment]
Implemented now in the current beta for 9.2.0

**Pull request closed without merging**
