### PR TITLE
Option 'Force friendly in combat' extended to allow to force normal healthbar

### PR DESCRIPTION
**Pull request by sslebedev**
There is an option to force friendly headline view while in combat (when normally it is healthbar). But there is no way to set up opposite situations: headline view out of combat and healtbars in combat. This is really useful setup with BFA world pvp, for example.

So I've changed this Force option's functionality to allow this. Unfortunately, I didn't manage to maintain backward compatibility, but I am sure, very few people use this option.

I am playing with this version for about a week and didn't catch any related bugs or exceptions, but I'll keep an eye on it.

### CODE REVIEW

**Comment by Backupiseasy** [comment]
Hi sslebedev, 

I'll take a look at your changes in the next few days. I would rather like to have both features to be available, that's my goal as the inital implementation was also requested by an user.

**Comment by sslebedev** [comment]
Hi,
I agree, that's why my implementation converts this options to a kinda 'tristate': those three options (force nothing, force name, force healthbar) are exclusive and obviously cannot be active at the same time. The backward compatibility issue I've mentioned means only I didn't find a way to silently convert old boolean type persistent data to an enumerable, but it is still possible to set old force mode again. I've broken nothing in it, just old checkbox value will be lost until user set it up again in dropdown selector

**Comment by Backupiseasy** [comment]
Ok, now I understand. I've implemented several functions for migrating deprecated values, you can look at Database.lua - MigrateDatabase for an idea how that works.

**Comment by Backupiseasy** [comment]
I plan to integrate it into the first alpha for 9.1.0 (branch devel/91/main) - hopefully that's something I can finish next weekend. There's still a lot to do until 9.1 is finished, but a working, testable alpha version should be possible in the next few days.

**Comment by sslebedev** [comment]
Wrote 9.1.0 version for this change in feature branch

**Comment by Backupiseasy** [comment]
I think the changes are ok. I'll integrate them into 9.1. I probably will re-write the following code

```
  elseif db.ForceFriendlyInCombat == "HEADLINE" and unit.reaction == "FRIENDLY" and InCombatLockdown() then
    headline_view = true
  elseif db.ForceFriendlyInCombat == "NORMAL" and unit.reaction == "FRIENDLY" and InCombatLockdown() then
    headline_view = false
```

to something like 

```
  elseif unit.reaction == "FRIENDLY" and InCombatLockdown() then
    if db.ForceFriendlyInCombat == "HEADLINE" then
      headline_view = true
    elseif db.ForceFriendlyInCombat == "NORMAL" then
      headline_view = false
```

to avoid redundant comparisons.

**Comment by Backupiseasy** [comment]
Merged this request now into the devel/91/main branch.

**Pull request merged**
