### PR TITLE
SOD Nameplate Castbar Fixes

### PR DESCRIPTION
**Pull request by fbrusch-ik**
Hey ! 
In SOD many of the spell ids got switched around which confuses LibClassicCasterino so it does not show all casts.

The good news is that technically you dont need LibClassicCasterino at all anymore since you can just listen to the events and use the UnitCastingInfo / UnitChannelInfo directly from the WoW API.

The bad news is that the UnitChannelInfo Event is bugged and only returns a bunch of nils, so we still need LibClassicCasterino for that. 

I added penance as a new channel to show show  how it is done.

### CODE REVIEW

**Comment by danjohnso** [comment]
Been running with this PR for 2 weeks now, no issues that I have noticed, seems like all the castbars are appearing as expected

**Comment by Backupiseasy** [comment]
I also think that having separate parts for Addon.IS_CLASSIC_SOD and Addon.IS_CLASSIC is necssary. There is no Addon.IS_CLASSIC without SOD when it comes to funcionality, i.e., the changes you made to Addon.IS_CLASSIC_SOD should also work on plain Classic servers. So, you can merge that I think.

**Comment by Backupiseasy** [comment]
See my comment here: https://github.com/Backupiseasy/ThreatPlates/issues/493

I did not merge your PR as it is behind the current branch (devel/111/main), but used your changes.

**Comment by fbrusch-ik** [comment]
Hey! 
Dont worry, that what my main intention behind this anyway

**Pull request closed without merging**
