### PR TITLE
HealerTrackerWidget enhancements

### PR DESCRIPTION
**Pull request by Kungfumoo**
- fixed indentation
- it is using hash tables now
- also added handling for DK Dark Simulacrum (came up when I was testing)

### CODE REVIEW

**Comment by Backupiseasy** [comment]
As I won't be able to release 8.8 before WoW 8.0 hits live servers, I created a new branch devel/90/main for the release 9.0.0 of Threat Plates. It's based on the old devel/88/main branch and already contains your changes from above.

**Comment by Kungfumoo** [comment]
Cool, thanks

**Comment by Kungfumoo** [comment]
Oh yeah, don't forget about
https://github.com/Backupiseasy/ThreatPlates/blob/3cc09b4dc08cdb3cc3af17e1723fde2f67c83531/Widgets/HealerTrackerWidget.lua#L175

for bfa

**Comment by Backupiseasy** [comment]
Yeah, there are several lines like that in the source code currently :) Makes it easier to find the lines where I have to change code when the WoW patch goes live.

**Pull request merged**
